[package]
name = "protolang-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = "0.7"
clap = { version = "4", features = ["derive"] }
inquire = "0.6"
