workspace = { members = ["protolang-cli"] }
[package]
name = "protolang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
werbolg-compile = { version = "0.1", git = "https://github.com/vincenthz/werbolg" }
werbolg-exec = { version = "0.1", git = "https://github.com/vincenthz/werbolg" }
werbolg-core = { version = "0.1", git = "https://github.com/vincenthz/werbolg" }
werbolg-lang-common = { version = "0.1", git = "https://github.com/vincenthz/werbolg" }
werbolg-lang-rusty = { version = "0.1", git = "https://github.com/vincenthz/werbolg" }
